version: 2
updates:
- package-ecosystem: pip
  directory: "/backend/kollox"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: astroid
    versions:
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: prompt-toolkit
    versions:
    - 3.0.15
    - 3.0.16
    - 3.0.17
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
  - dependency-name: pygments
    versions:
    - 2.8.0
  - dependency-name: cryptography
    versions:
    - 3.4.1
  - dependency-name: autopep8
    versions:
    - 1.5.5
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: vuetify
    versions:
    - 2.4.11
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.7
    - 1.32.8
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.1.0
    - 2.2.0
    - 2.2.2
    - 2.3.0
    - 2.3.1
