# Generated by Django 3.1.3 on 2020-11-14 10:50

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[authentication.validators.validate_age], verbose_name='Age'),
        ),
    ]
