# Generated by Django 3.1.3 on 2020-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201212_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='noimage.png', upload_to='d:/repos/kollox/frontend/src/assets/'),
        ),
    ]
