# Generated by Django 3.1.3 on 2020-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201215_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='noimage.png', upload_to='assets/avatars/'),
        ),
    ]
