# Generated by Django 3.1.3 on 2020-11-13 18:24

import authentication.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='none', max_length=512, verbose_name='ToDo-List Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_completed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[authentication.validators.percent_validation], verbose_name='Completed Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_archive', 'In Archive'), ('started', 'Started'), ('completed', 'Completed'), ('not_complted', 'Not Completed')], default='not_started', max_length=256, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='simpletodolist',
            name='name',
            field=models.CharField(default='none', max_length=512, verbose_name='ToDo-List Name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Desctiption')),
                ('todo_list_id', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('subtask', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todoitem')),
                ('todo_list_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
