# Generated by Django 3.1.3 on 2020-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201215_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(default='https://cdn.vuetifyjs.com/images/cards/sunshine.jpg', upload_to='assets/avatars/'),
        ),
        migrations.AddField(
            model_name='simpletodolist',
            name='cover',
            field=models.ImageField(default='https://cdn.vuetifyjs.com/images/cards/sunshine.jpg', upload_to='assets/avatars/'),
        ),
        migrations.AlterField(
            model_name='simpletodolist',
            name='status',
            field=models.CharField(choices=[('in_archive', 'In Archive'), ('started', 'Started'), ('completed', 'Completed'), ('not_completed', 'Not Completed'), ('not_started', 'Not Started')], default='not_started', max_length=255, verbose_name='Status'),
        ),
    ]
