# Generated by Django 3.1.3 on 2020-12-19 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20201215_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['is_completed'], 'verbose_name': 'Todo Item'},
        ),
        migrations.AddField(
            model_name='project',
            name='shared_owners',
            field=models.ManyToManyField(related_name='shared_projects', to=settings.AUTH_USER_MODEL, verbose_name='Shared Owner'),
        ),
        migrations.AddField(
            model_name='simpletodolist',
            name='shared_owners',
            field=models.ManyToManyField(related_name='shared_lists', to=settings.AUTH_USER_MODEL, verbose_name='Shared Owner'),
        ),
    ]
