# Generated by Django 3.1.3 on 2020-12-28 20:42

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201219_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='assets/covers/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['is_completed', '-started_time'], 'verbose_name': 'Todo Item'},
        ),
    ]
