# Generated by Django 3.1.3 on 2020-11-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201114_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpletodolist',
            options={'verbose_name': 'Simple ToDo List'},
        ),
    ]
