# Generated by Django 3.1.3 on 2020-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201114_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletodolist',
            name='status',
            field=models.CharField(choices=[('in_archive', 'In Archive'), ('started', 'Started'), ('completed', 'Completed'), ('not_complted', 'Not Completed'), ('not_started', 'Not Started')], default='not_started', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_archive', 'In Archive'), ('started', 'Started'), ('completed', 'Completed'), ('not_complted', 'Not Completed'), ('not_started', 'Not Started')], default='not_started', max_length=256, verbose_name='Status'),
        ),
    ]
