# Generated by Django 3.1.3 on 2020-11-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201114_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Desctiption'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todoitem'),
        ),
    ]
